# Generated by Django 4.0.6 on 2022-07-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
