# Generated by Django 4.0.6 on 2022-07-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0008_blogs_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blogname',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentatorname',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
